### PR TITLE
Defines and uses a custom io.Writer for logging which can search and replace tokens. Closes #612. Closes #283

### LINKED ISSUE #283: Logger not printing message with newline character `\n` correctly
There is an issue with the Steampipe logger while printing messages with newline charater `\n`

For instance:
```plugin.Logger(ctx).Error("snowflake_user.DescribeUser", "TEST.error", "SQL access control error:\nInsufficient privileges to operate on user 'SNOWFLAKE'")``` prints only part prior to `\n` in the log

```
2022-03-04 12:00:25.723 UTC [ERROR] steampipe-plugin-snowflake.plugin: [ERROR] snowflake_user.DescribeUser: TEST.error="SQL access control error:
```

### LINKED ISSUE #612: Use custom `io.Writer` in plugin logger in SDK.

### PR DESCRIPTION
**Pull request by binaek**
Screenshot 2023-07-31 at 7 28 19 PM

### CODE REVIEW

File: logging/mappingwriter.go [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+import (
+	"bytes"
+	"io"
+)
+
+type newLineEscapeWriter struct {
+	wr io.Writer
+}
+
+func NewLineEscapeWriter(writer io.Writer) newLineEscapeWriter {
```
Comment (kaidaguerre) [inline logging/mappingwriter.go:12]: I think `NewlineEscapeWriter`

File: logging/mappingwriter.go [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+	return newLineEscapeWriter{
+		wr: writer,
+	}
+}
+
+func (m newLineEscapeWriter) Write(in []byte) (n int, err error) {
+	hasSuffixNewLine := bytes.HasSuffix(in, []byte("\n"))
+	escaped := []byte{}
+	if hasSuffixNewLine {
```
Comment (kaidaguerre) [inline logging/mappingwriter.go:21]: why is  this needed?

**Review by kaidaguerre — CHANGES_REQUESTED** [review]

File: logging/mappingwriter.go (hunk 2 above)
Comment (kaidaguerre) [reply logging/mappingwriter.go:21]: add comment

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
